### ISSUE TITLE
Add a LICENSE file

### ISSUE THREAD

**Issue by amitness** [sarojdhakal/Bhasha#1]
Great initiative to share these resources with the community.

You could add a LICENSE file in the repo. This [site](https://choosealicense.com/) can help you choose the license suitable for this.

Once chosen, just select `Create New File` in GitHub interface, set filename as `LICENSE` and GitHub will show the options dropdown in the sidebar. Choose the LICENSE from there.

**Comment by sarojdhakal** [comment]
Thanks Amit,

I plan to share more, those I have prepared over the years.

Thanks,
Saroj
